name: Mocha Tests

on:
  push:
    branches: [ dev ]
    paths:
    - '**.js'
    - '**.json'
  pull_request:
    branches: [ dev ]
    paths:
    - '**.js'
    - '**.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run mocha tests
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run test
      env:
        CI: true
